{% set name = "boule" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe8ac535ebd960ee14945ecb1650ace607afbfe9ae19c496ff95a8be5a495b34

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - attrs

test:
  imports:
    - boule

about:
  home: https://github.com/fatiando/boule
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Reference ellipsoids for geodesy, geophysics, and coordinate calculations
  description: |
    Boule is Python library for representing Reference Ellipsoids, calculating
    their gravity fields, and converting coordinates defined on the ellipsoids.
    The main use cases are 1) calculating normal gravity (for gravity anomalies
    and disturbances); 2) spherical gravity modeling, which requires geodetic
    to geocentric spherical coordinate conversions; 3) input ellipsoid
    parameters for spherical harmonic analysis. Boule is French for ball and
    also a traditional shape of bread resembling a squashed ball (much like the
    Earth).
  doc_url: https://www.fatiando.org/boule/
  dev_url: https://github.com/fatiando/boule

extra:
  recipe-maintainers:
    - leouieda
