{% set name = "boule" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee74bec713b9694154aaffafc8ba99f448e6cd1bd59b73b9986804570c7fcad3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - setuptools_scm >=8.0.3
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - attrs >=19.3.0
    - scipy >=1.8.0

test:
  requires:
    - python  {{ python_min }}
  imports:
    - boule

about:
  home: https://github.com/fatiando/boule
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Reference ellipsoids for geodesy and geophysics
  description: |
    Boule is Python library for representing Reference Ellipsoids, calculating
    their gravity fields, and converting coordinates defined on the ellipsoids.
    The main use cases are 1) calculating normal gravity (for gravity anomalies
    and disturbances); 2) spherical gravity modeling, which requires geodetic
    to geocentric spherical coordinate conversions; 3) input ellipsoid
    parameters for spherical harmonic analysis. Boule is French for ball and
    also a traditional shape of bread resembling a squashed ball (much like the
    Earth).
  doc_url: https://www.fatiando.org/boule/
  dev_url: https://github.com/fatiando/boule

extra:
  recipe-maintainers:
    - leouieda
    - santisoler
