{% set name = "boule" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bcc519acb15041df0f0a5a2ac4dbc8ed8ee47f887a72891e5a86222e3ac68b60

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - numpy
    - attrs

test:
  imports:
    - boule

about:
  home: https://github.com/fatiando/boule
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Reference ellipsoids for geodesy and geophysics
  description: |
    Boule is Python library for representing Reference Ellipsoids, calculating
    their gravity fields, and converting coordinates defined on the ellipsoids.
    The main use cases are 1) calculating normal gravity (for gravity anomalies
    and disturbances); 2) spherical gravity modeling, which requires geodetic
    to geocentric spherical coordinate conversions; 3) input ellipsoid
    parameters for spherical harmonic analysis. Boule is French for ball and
    also a traditional shape of bread resembling a squashed ball (much like the
    Earth).
  doc_url: https://www.fatiando.org/boule/
  dev_url: https://github.com/fatiando/boule

extra:
  recipe-maintainers:
    - leouieda
