travis:
  secure:
    BINSTAR_TOKEN: ImFoliJlQCRr9VWAxsgG9ucSJrV2igAy6p0nU3LcMs9DocG+AL7XdYTf1m6lT5XzMkXOWycvYiyK8MsUpePE2ce7XzI2L/BYedbInpzZEIlJEeyZpAZJwLOCD4WAqEUz6heRFv6Yr9ZQef8XeHklOrBbVWRWatOrYX913xBkD7/8MXegZsAuU8mtYuBdafWQHvfEV1cqdKq8PhnF2iW4H0EFw/e8Re0rlpyTkg5UVdqQ7N63ZL7L78Y9OptFJpT9Onp7YaoJJySI+Z10YqzHZZXdiGejebL78W+PGNY3SedXs6/rsJEthNGX81Z1+Zcc8kH+I9WteuaX7VNFD1QpnIuQ9TE8GyA6jIGXc5m/+ERxMDbqgqYfkSbd7ngh25Jo3rlns0sOAZeKIlFJC8lKTrl/MmmDrVnPlBH2H0No0dLR6OlJkcAFbFFa4XRrwRF5yQpaxNO8e8IXcvyenXpkMwhY0BEsDZ5O9giJfwFFABlpGVFCFuSZb7GL9uzLcO4wwrfKM2RGXyvPW+hyZwmfuR+Cp0Wg0OLH9YK2hPX/S7+3YUQEyfkfRsp1B+ux7Ve7StKfgQreK+jsgbnDDYX/mVlx5T0T7jwPtnwc7CvO/UnzUiLGI1fhSNDEmbv1y1ppuOOn9h6yfucfF1jgpGP1v3Cl/B8B8AvUpB06kYj+Fh0=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
